# Use official Tomcat image
FROM tomcat:10.1.12-jdk17

# Remove default ROOT webapp
RUN rm -rf /usr/local/tomcat/webapps/*

# Create uploads folder inside container
RUN mkdir -p /app/uploads
RUN chmod -R 777 /app/uploads

# Copy WAR file to Tomcat webapps as ROOT.war
COPY target/blog.war /usr/local/tomcat/webapps/ROOT.war

# Expose Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
